// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Lif3EPMzDPVLNo2MjQmZ5wnjnrjgBJ8',
    appId: '1:855807778855:web:1633d1f28d2f916b94ee02',
    messagingSenderId: '855807778855',
    projectId: 'vmsproject-9884d',
    authDomain: 'vmsproject-9884d.firebaseapp.com',
    storageBucket: 'vmsproject-9884d.firebasestorage.app',
    measurementId: 'G-4CHVG09D6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWjO5bq0hWdDR8V-8ZmDRNez3jGgJ8OA',
    appId: '1:855807778855:android:9f17d2dafbf4545e94ee02',
    messagingSenderId: '855807778855',
    projectId: 'vmsproject-9884d',
    storageBucket: 'vmsproject-9884d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMw-0LsZ944DX1GjuH8fbCExpaUprB6U',
    appId: '1:855807778855:ios:4c119c684e28a76e94ee02',
    messagingSenderId: '855807778855',
    projectId: 'vmsproject-9884d',
    storageBucket: 'vmsproject-9884d.firebasestorage.app',
    iosBundleId: 'com.example.vms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMw-0LsZ944DX1GjuH8fbCExpaUprB6U',
    appId: '1:855807778855:ios:4c119c684e28a76e94ee02',
    messagingSenderId: '855807778855',
    projectId: 'vmsproject-9884d',
    storageBucket: 'vmsproject-9884d.firebasestorage.app',
    iosBundleId: 'com.example.vms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Lif3EPMzDPVLNo2MjQmZ5wnjnrjgBJ8',
    appId: '1:855807778855:web:4bf1aebe4ac0adf194ee02',
    messagingSenderId: '855807778855',
    projectId: 'vmsproject-9884d',
    authDomain: 'vmsproject-9884d.firebaseapp.com',
    storageBucket: 'vmsproject-9884d.firebasestorage.app',
    measurementId: 'G-FJTVWP0J7Q',
  );
}
